# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import dfs_pb2 as proto_dot_dfs__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/dfs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NameNodeServiceStub(object):
    """============================================================
    NameNode Service – Gestión de metadatos y coordinación
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/dfs.NameNodeService/Register',
                request_serializer=proto_dot_dfs__pb2.RegisterRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/dfs.NameNodeService/Login',
                request_serializer=proto_dot_dfs__pb2.LoginRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.PutFile = channel.unary_unary(
                '/dfs.NameNodeService/PutFile',
                request_serializer=proto_dot_dfs__pb2.PutFileRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.PutFileResponse.FromString,
                _registered_method=True)
        self.GetFile = channel.unary_unary(
                '/dfs.NameNodeService/GetFile',
                request_serializer=proto_dot_dfs__pb2.GetFileRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.GetFileResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/dfs.NameNodeService/DeleteFile',
                request_serializer=proto_dot_dfs__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.DeleteFileResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/dfs.NameNodeService/ListFiles',
                request_serializer=proto_dot_dfs__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.MakeDir = channel.unary_unary(
                '/dfs.NameNodeService/MakeDir',
                request_serializer=proto_dot_dfs__pb2.MakeDirRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.MakeDirResponse.FromString,
                _registered_method=True)
        self.RemoveDir = channel.unary_unary(
                '/dfs.NameNodeService/RemoveDir',
                request_serializer=proto_dot_dfs__pb2.RemoveDirRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.RemoveDirResponse.FromString,
                _registered_method=True)
        self.GetClusterStatus = channel.unary_unary(
                '/dfs.NameNodeService/GetClusterStatus',
                request_serializer=proto_dot_dfs__pb2.ClusterStatusRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.ClusterStatusResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/dfs.NameNodeService/Heartbeat',
                request_serializer=proto_dot_dfs__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.BlockReport = channel.unary_unary(
                '/dfs.NameNodeService/BlockReport',
                request_serializer=proto_dot_dfs__pb2.BlockReportRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.BlockReportResponse.FromString,
                _registered_method=True)
        self.ConfirmBlock = channel.unary_unary(
                '/dfs.NameNodeService/ConfirmBlock',
                request_serializer=proto_dot_dfs__pb2.ConfirmBlockRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.ConfirmBlockResponse.FromString,
                _registered_method=True)
        self.ReportCorruptBlock = channel.unary_unary(
                '/dfs.NameNodeService/ReportCorruptBlock',
                request_serializer=proto_dot_dfs__pb2.ReportCorruptBlockRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.ReportCorruptBlockResponse.FromString,
                _registered_method=True)


class NameNodeServiceServicer(object):
    """============================================================
    NameNode Service – Gestión de metadatos y coordinación
    ============================================================
    """

    def Register(self, request, context):
        """Auth
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutFile(self, request, context):
        """Operaciones de archivos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeDir(self, request, context):
        """Namespace (directorios)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterStatus(self, request, context):
        """Estado del clúster (para CLI status)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """DataNode → NameNode
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmBlock(self, request, context):
        """Confirmar bloques almacenados (cliente → NameNode tras PUT)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportCorruptBlock(self, request, context):
        """Reportar bloque corrupto
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=proto_dot_dfs__pb2.RegisterRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.RegisterResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=proto_dot_dfs__pb2.LoginRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.LoginResponse.SerializeToString,
            ),
            'PutFile': grpc.unary_unary_rpc_method_handler(
                    servicer.PutFile,
                    request_deserializer=proto_dot_dfs__pb2.PutFileRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.PutFileResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=proto_dot_dfs__pb2.GetFileRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.GetFileResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=proto_dot_dfs__pb2.DeleteFileRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.DeleteFileResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=proto_dot_dfs__pb2.ListFilesRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.ListFilesResponse.SerializeToString,
            ),
            'MakeDir': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeDir,
                    request_deserializer=proto_dot_dfs__pb2.MakeDirRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.MakeDirResponse.SerializeToString,
            ),
            'RemoveDir': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveDir,
                    request_deserializer=proto_dot_dfs__pb2.RemoveDirRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.RemoveDirResponse.SerializeToString,
            ),
            'GetClusterStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterStatus,
                    request_deserializer=proto_dot_dfs__pb2.ClusterStatusRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.ClusterStatusResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=proto_dot_dfs__pb2.HeartbeatRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.HeartbeatResponse.SerializeToString,
            ),
            'BlockReport': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockReport,
                    request_deserializer=proto_dot_dfs__pb2.BlockReportRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.BlockReportResponse.SerializeToString,
            ),
            'ConfirmBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmBlock,
                    request_deserializer=proto_dot_dfs__pb2.ConfirmBlockRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.ConfirmBlockResponse.SerializeToString,
            ),
            'ReportCorruptBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportCorruptBlock,
                    request_deserializer=proto_dot_dfs__pb2.ReportCorruptBlockRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.ReportCorruptBlockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfs.NameNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfs.NameNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NameNodeService(object):
    """============================================================
    NameNode Service – Gestión de metadatos y coordinación
    ============================================================
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.NameNodeService/Register',
            proto_dot_dfs__pb2.RegisterRequest.SerializeToString,
            proto_dot_dfs__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.NameNodeService/Login',
            proto_dot_dfs__pb2.LoginRequest.SerializeToString,
            proto_dot_dfs__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.NameNodeService/PutFile',
            proto_dot_dfs__pb2.PutFileRequest.SerializeToString,
            proto_dot_dfs__pb2.PutFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.NameNodeService/GetFile',
            proto_dot_dfs__pb2.GetFileRequest.SerializeToString,
            proto_dot_dfs__pb2.GetFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.NameNodeService/DeleteFile',
            proto_dot_dfs__pb2.DeleteFileRequest.SerializeToString,
            proto_dot_dfs__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.NameNodeService/ListFiles',
            proto_dot_dfs__pb2.ListFilesRequest.SerializeToString,
            proto_dot_dfs__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.NameNodeService/MakeDir',
            proto_dot_dfs__pb2.MakeDirRequest.SerializeToString,
            proto_dot_dfs__pb2.MakeDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.NameNodeService/RemoveDir',
            proto_dot_dfs__pb2.RemoveDirRequest.SerializeToString,
            proto_dot_dfs__pb2.RemoveDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.NameNodeService/GetClusterStatus',
            proto_dot_dfs__pb2.ClusterStatusRequest.SerializeToString,
            proto_dot_dfs__pb2.ClusterStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.NameNodeService/Heartbeat',
            proto_dot_dfs__pb2.HeartbeatRequest.SerializeToString,
            proto_dot_dfs__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BlockReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.NameNodeService/BlockReport',
            proto_dot_dfs__pb2.BlockReportRequest.SerializeToString,
            proto_dot_dfs__pb2.BlockReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.NameNodeService/ConfirmBlock',
            proto_dot_dfs__pb2.ConfirmBlockRequest.SerializeToString,
            proto_dot_dfs__pb2.ConfirmBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportCorruptBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.NameNodeService/ReportCorruptBlock',
            proto_dot_dfs__pb2.ReportCorruptBlockRequest.SerializeToString,
            proto_dot_dfs__pb2.ReportCorruptBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataNodeServiceStub(object):
    """============================================================
    DataNode Service – Almacenamiento y transferencia de bloques
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreBlock = channel.stream_unary(
                '/dfs.DataNodeService/StoreBlock',
                request_serializer=proto_dot_dfs__pb2.StoreBlockRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.StoreBlockResponse.FromString,
                _registered_method=True)
        self.RetrieveBlock = channel.unary_stream(
                '/dfs.DataNodeService/RetrieveBlock',
                request_serializer=proto_dot_dfs__pb2.RetrieveBlockRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.RetrieveBlockResponse.FromString,
                _registered_method=True)
        self.ReplicateBlock = channel.unary_unary(
                '/dfs.DataNodeService/ReplicateBlock',
                request_serializer=proto_dot_dfs__pb2.ReplicateBlockRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.ReplicateBlockResponse.FromString,
                _registered_method=True)
        self.DeleteBlock = channel.unary_unary(
                '/dfs.DataNodeService/DeleteBlock',
                request_serializer=proto_dot_dfs__pb2.DeleteBlockRequest.SerializeToString,
                response_deserializer=proto_dot_dfs__pb2.DeleteBlockResponse.FromString,
                _registered_method=True)


class DataNodeServiceServicer(object):
    """============================================================
    DataNode Service – Almacenamiento y transferencia de bloques
    ============================================================
    """

    def StoreBlock(self, request_iterator, context):
        """Cliente → DataNode (streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveBlock(self, request, context):
        """DataNode → Cliente (streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateBlock(self, request, context):
        """DataNode → DataNode (replicación pipeline)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBlock(self, request, context):
        """NameNode → DataNode
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreBlock': grpc.stream_unary_rpc_method_handler(
                    servicer.StoreBlock,
                    request_deserializer=proto_dot_dfs__pb2.StoreBlockRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.StoreBlockResponse.SerializeToString,
            ),
            'RetrieveBlock': grpc.unary_stream_rpc_method_handler(
                    servicer.RetrieveBlock,
                    request_deserializer=proto_dot_dfs__pb2.RetrieveBlockRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.RetrieveBlockResponse.SerializeToString,
            ),
            'ReplicateBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateBlock,
                    request_deserializer=proto_dot_dfs__pb2.ReplicateBlockRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.ReplicateBlockResponse.SerializeToString,
            ),
            'DeleteBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBlock,
                    request_deserializer=proto_dot_dfs__pb2.DeleteBlockRequest.FromString,
                    response_serializer=proto_dot_dfs__pb2.DeleteBlockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfs.DataNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfs.DataNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataNodeService(object):
    """============================================================
    DataNode Service – Almacenamiento y transferencia de bloques
    ============================================================
    """

    @staticmethod
    def StoreBlock(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dfs.DataNodeService/StoreBlock',
            proto_dot_dfs__pb2.StoreBlockRequest.SerializeToString,
            proto_dot_dfs__pb2.StoreBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dfs.DataNodeService/RetrieveBlock',
            proto_dot_dfs__pb2.RetrieveBlockRequest.SerializeToString,
            proto_dot_dfs__pb2.RetrieveBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.DataNodeService/ReplicateBlock',
            proto_dot_dfs__pb2.ReplicateBlockRequest.SerializeToString,
            proto_dot_dfs__pb2.ReplicateBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfs.DataNodeService/DeleteBlock',
            proto_dot_dfs__pb2.DeleteBlockRequest.SerializeToString,
            proto_dot_dfs__pb2.DeleteBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
